custom: ['https://paypal.me/Surra00?country.x=IT&locale.x=it_IT', 'https://www.blockchain.com/btc/address/bc1q9u3jul3eenqqgx20762fs6wzmf9dqd5auc976m','https://etherscan.io/address/0x8440dA249c3A4ea6a5d7c6aa89691780547e2D92']

